name: CustomMeteorites
main: me.n1xend.meteorites.CustomMeteorites
version: 2.0.0
api-version: '1.20'
author: n1xend
description: Custom meteorites with persistent cleanup, loot, effects, radar and guardians.

commands:
  meteor:
    description: Meteorite management command
    usage: /meteor <spawn|start|stop|reload|version> [id]
    permission: custommeteorites.admin

permissions:
  custommeteorites.admin:
    description: Allows using /meteor admin commands
    default: op