name: CustomMeteorites
main: me.n1xend.meteorites.CustomMeteorites
version: 1.0.1
api-version: '1.20'
author: n1xend
description: Custom meteorites with loot, rarity, effects, radar and guardians.

commands:
  meteor:
    description: Meteorite management command
    usage: /meteor <spawn|start|stop|reload> [id]
    permission: custommeteorites.admin

permissions:
  custommeteorites.admin:
    description: Allows using /meteor admin commands
    default: op
